name: Update README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name Sandovl0593
        git config user.email adrian.sandoval@utec.edu.pe
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with info pregraduate"
        git push origin main