name: Update README.md

on:
  push:
    branches:
      - main
        
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Updating info
      run: |
        node src/index.cjs
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "[bot] Update README with info pregraduate"
        git push origin main